namespace Famick.HomeManagement.Core.Interfaces.Plugins;

/// <summary>
/// Result from a product lookup search
/// </summary>
public class ProductLookupResult
{
    /// <summary>
    /// Data sources that contributed to this result.
    /// Key = Plugin DisplayName, Value = External ID from that source
    /// </summary>
    public Dictionary<string, string> DataSources { get; set; } = new();

    /// <summary>
    /// Product name/description
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Brand name (if available)
    /// </summary>
    public string? BrandName { get; set; }

    /// <summary>
    /// Brand owner/manufacturer (if available)
    /// </summary>
    public string? BrandOwner { get; set; }

    /// <summary>
    /// Barcode (UPC/EAN) if available - this is the barcode returned by the plugin
    /// </summary>
    public string? Barcode { get; set; }

    /// <summary>
    /// The originally scanned/searched barcode (if different from plugin-returned barcode).
    /// Used to store both formats (e.g., 12-digit UPC and 13-digit EAN) when they differ.
    /// </summary>
    public string? OriginalSearchBarcode { get; set; }

    /// <summary>
    /// Food category (e.g., "Cheese", "Snacks", "Beverages")
    /// </summary>
    public List<string> Categories { get; set; } = new();

    /// <summary>
    /// Product image (if available). First plugin to provide wins.
    /// </summary>
    public ResultImage? ImageUrl { get; set; }

    /// <summary>
    /// URL to product thumbnail image (if available)
    /// </summary>
    public ResultImage? ThumbnailUrl { get; set; }

    /// <summary>
    /// Serving size description
    /// </summary>
    public string? ServingSizeDescription { get; set; }

    /// <summary>
    /// Ingredients list (if available)
    /// </summary>
    public string? Ingredients { get; set; }

    /// <summary>
    /// Nutrition information (if available)
    /// </summary>
    public ProductLookupNutrition? Nutrition { get; set; }

    /// <summary>
    /// Additional data from the source (plugin-specific)
    /// </summary>
    public Dictionary<string, object>? AdditionalData { get; set; }

    /// <summary>
    /// Description of the product
    /// </summary>
    public string? Description { get; set; }

    // ===== Store integration fields =====

    /// <summary>
    /// Current price at the store
    /// </summary>
    public decimal? Price { get; set; }

    /// <summary>
    /// Price unit (e.g., "each", "lb")
    /// </summary>
    public string? PriceUnit { get; set; }

    /// <summary>
    /// Sale/promotional price
    /// </summary>
    public decimal? SalePrice { get; set; }

    /// <summary>
    /// Aisle location in the store
    /// </summary>
    public string? Aisle { get; set; }

    /// <summary>
    /// Shelf location in the store
    /// </summary>
    public string? Shelf { get; set; }

    /// <summary>
    /// Department or category in the store
    /// </summary>
    public string? Department { get; set; }

    /// <summary>
    /// Whether the product is currently in stock
    /// </summary>
    public bool? InStock { get; set; }

    /// <summary>
    /// Product size/weight description
    /// </summary>
    public string? Size { get; set; }

    /// <summary>
    /// URL to the product page on the store's website
    /// </summary>
    public string? ProductUrl { get; set; }

    /// <summary>
    /// Store's internal product ID/SKU
    /// </summary>
    public string? ExternalProductId { get; set; }

    /// <summary>
    /// Shopping location ID where this product was found
    /// </summary>
    public Guid? ShoppingLocationId { get; set; }

    /// <summary>
    /// Shopping location name where this product was found
    /// </summary>
    public string? ShoppingLocationName { get; set; }

    /// <summary>
    /// Markdown-formatted attribution text generated by the plugin for this result.
    /// Each plugin writes its own attribution (with correct barcode URLs, license, etc.).
    /// The service concatenates attributions from all contributing plugins when storing.
    /// </summary>
    public string? AttributionMarkdown { get; set; }
}
